{
  # robot configurations, 0->right 1->left
  # comment out robot #1 if only using 1 arm
  "robots": [
    {
      "robot_type": "piper",
      "piper_can": "can0",
      "robot_obs_latency": 0.0001, "robot_action_latency": 0.05, "tcp_offset": 0.182,
      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": -0.010,
      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.1, "sphere_center": [0, -0.06, -0.185]
    },
    {
      "robot_type": "piper",
      "piper_can": "can1",
      "robot_obs_latency": 0.0001, "robot_action_latency": 0.05, "tcp_offset": 0.182,
      # table height for finger-table collision avoidance
      # -inf to disable
      "height_threshold": -0.010,
      # sphere collision primitive size and location for inter-gripper collision avoidance
      # 0 to disable
      "sphere_radius": 0.1, "sphere_center": [0, -0.06, -0.185]
    }
  ],
  # gripper configurations, 0->right 1->left
  "grippers": [
    {
      "gripper_type": "pika",
      "gripper_serial": "/dev/ttyUSB81",
      "gripper_obs_latency": 0.01, 
      "gripper_action_latency": 0.1
    },
    {
      "gripper_type": "pika",
      "gripper_serial": "/dev/ttyUSB82",
      "gripper_obs_latency": 0.01, 
      "gripper_action_latency": 0.1
    },
  ],
  # transformation right arm's base frame in left arm's base coordinate frame
  "tx_left_right": [
    [ -1.0,  0.0,  0.0    , 0.9],
    [ 0.0 , -1.0,  0.0    , 0.0],
    [0.0 ,   0.0,  1.0    , 0.0],
    [ 0. ,  0.  ,  0.     ,  1.]
  ],
  "cameras": { 
    "dev_video_paths": ["/dev/video81", "/dev/video82"], 
    "resolution": [ [640,480], [640,480] ], 
    "capture_fps": [30,30] 
  }
}
